#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

sketchybar --bar \
    height=28 \
    # color=0x66494d64 \
    margin=0 \
    sticky=on \
    padding_left=0 \
    padding_right=2 \
    notch_width=188 \
    display=all

sketchybar --default \
    background.height=24 \
    background.corner_radius=100 \
    icon.color=0xff24273a \
    icon.font="$FONT_FACE:Medium:13.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xff24273a \
    label.font="$FONT_FACE:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=5 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=10 \
    background.padding_right=0 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    label.padding_left=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
