#!/usr/bin/env sh

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa

# --- Events
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.dotfiles/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.dotfiles/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/scripts/create_spaces.sh

# --- Move space 6 to second display
yabai -m space 6 --display 2

# --- Assign space 9 to the second display
yabai -m display --add 2 --space 6

# --- Global settings
yabai -m config \
  external_bar all:35:0                   \
  mouse_follows_focus        off          \
  focus_follows_mouse        off          \
                                          \
  window_border              on           \
  window_zoom_persist        off          \
  window_placement           second_child \
  window_topmost             off          \
  window_shadow              float        \
  window_opacity             off          \
  window_opacity_duration    0.0          \
  active_window_opacity      1.0          \
  normal_window_opacity      0.0          \
  window_border_width        2            \
  window_border_hidpi        off          \
  window_border_radius       11           \
  window_border_blur         off          \
  window_animation_duration  0            \
                                          \
  top_padding                1            \
  bottom_padding             4            \
  left_padding               4            \
  right_padding              4            \
  window_gap                 6            \
                                          \
  insert_feedback_color      0xff9dd274   \
  split_ratio                0.50         \
  auto_balance               off          \
  mouse_modifier             fn           \
  mouse_action1              move         \
  mouse_action2              resize       \
  mouse_drop_action          swap         \
  layout                     bsp

# --- Remove problematic apps
yabai -m rule --add app="^(Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# --- Arrange some applications automatically
yabai -m rule --add app="Google Chrome" space=^1
yabai -m rule --add app="Wezterm" space=2
yabai -m rule --add app="Code" space=3
yabai -m rule --add app="Notion" space=^4
yabai -m rule --add app="Finder" space=^4
yabai -m rule --add app="Slack" space=^5
yabai -m rule --add app="Discord" space=^5
yabai -m rule --add app="Gather" space=6
  
echo "yabai configuration loaded.."
